[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nova-osint"
version = "1.0.0"
description = "Nova - passive cybersecurity OSINT toolkit"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "typer",
    "rich",
    "dnspython"
]

[project.scripts]
nova = "nova.cli:app"

[tool.setuptools.packages.find]
include = ["nova*"]

